
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 111
#define YY_END_OF_BUFFER 112
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[388] =
    {   0,
        0,    0,    4,    4,    9,    9,   12,   12,  112,  110,
        2,    1,    1,   98,  110,  109,   94,   74,  110,   18,
       19,   92,   90,   24,   91,   17,   93,  100,  100,   76,
       16,   83,   73,   84,   75,   27,   20,   21,   80,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,   22,   79,   23,   97,    4,
        6,    5,    9,   10,  111,   12,   14,   13,    1,   82,
        0,  107,  109,   99,   78,    0,   95,   96,    0,  104,
        3,    8,  104,  102,    0,    0,  104,    0,  100,    0,
        0,    0,  100,    0,   26,   87,   85,   81,   86,   88,

      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,   44,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,   77,
        4,    5,    5,    7,    9,   12,   14,  107,    0,  106,
       25,  104,  104,    0,    0,  104,    0,  102,  102,    0,
        0,  103,    0,  104,    0,  101,    0,  101,  100,    0,
      100,   89,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,   43,  109,  109,
       47,  109,  109,   50,  109,  109,  109,  109,  109,  109,

      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,   64,   71,  109,  109,  109,  109,   15,    0,   11,
       11,    0,  104,  104,    0,    0,  104,  103,  103,    0,
      104,  104,    0,    0,  104,  101,  101,    0,  104,  104,
      101,    0,  100,    0,  109,  109,  109,  109,   32,  109,
       34,  109,  109,   37,   38,  109,  109,  109,  109,  109,
      109,   48,  109,    0,  108,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,   60,  109,  109,  105,
       65,  109,  109,  109,  104,    0,  104,    0,    0,    0,
        0,  104,  104,    0,  109,  109,  109,   31,   33,   35,

      109,  109,   40,   42,  109,  109,  109,    0,  109,  109,
      109,  109,  109,  109,   55,  109,  109,   58,  109,   61,
      109,  109,   67,   72,    0,  104,  109,   29,  109,   36,
      109,  109,  109,  109,   49,    0,  109,  109,  109,   53,
       54,   70,   56,  109,  109,   62,  109,  109,  104,  104,
        0,  109,   30,   39,   41,  109,  109,    0,   69,   51,
      109,  109,  109,  109,  109,   28,  109,  109,    0,  109,
       57,  109,  109,   66,  109,  109,    0,   52,  109,   63,
       45,   46,   68,  109,  109,   59,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   30,   32,   33,   32,
        7,    7,    7,    7,    7,   34,    7,    7,    7,   35,
        7,    7,    7,    7,    7,    7,    7,   36,    7,    7,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,    7,   51,   52,   53,   54,
       55,   56,    7,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    3,    1,    4,    5,    1,    1,    1,
        1,    1,    6,    1,    1,    1,    7,    1,    8,    8,
        8,    8,    1,    1,    1,    1,    1,    1,    1,    8,
        8,    8,    8,    9,   10,    5,    1,    4,    1,    1,
       11,    8,    8,    8,    8,    8,    8,    5,    5,    5,
        5,    9,    5,    5,    5,   10,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[406] =
    {   0,
        0,    0,   67,   68,   69,   71,   70,   71,  789,  790,
      790,  790,  785,  761,  780,    0,  759,   69,    0,  790,
      790,  758,   65,  790,   66,   66,   71,   93,  140,  760,
      790,   68,  756,   72,  790,  790,  790,  790,  755,   47,
       47,   54,  725,   65,   80,   90,  724,  108,   61,  732,
      106,   74,   78,  728,  726,  790,   74,  790,  790,    0,
      790,  129,    0,  790,  790,    0,  769,  790,  790,  790,
      768,  767,    0,  790,  790,  762,  790,  790,  754,  156,
      790,  790,  174,  205,  241,  129,  790,  194,  790,  753,
      212,  752,  223,  248,  790,  742,  790,  790,  790,  153,

      709,  708,  710,  718,  704,  703,  719,  718,  699,  700,
      697,  697,  703,  700,  698,  695,    0,  695,  124,  696,
      690,  686,  693,  694,  688,   96,  701,  684,  700,  686,
       59,  684,  685,  114,  176,  681,  117,  687,  690,  790,
        0,  140,  186,  790,    0,    0,  729,  790,  226,  790,
      790,  258,  790,  292,  274,  297,  306,    0,  790,  312,
      326,  171,  330,  336,    0,  231,    0,  320,    0,  343,
      354,  708,  674,  686,  679,  688,  683,  684,  670,  668,
      682,  678,  670,  676,  663,  678,  677,    0,  666,  658,
        0,  668,  665,    0,  698,  661,  659,  650,  651,  657,

      648,  655,  649,  646,  654,  657,  658,  643,  645,  645,
      652,    0,    0,  652,  654,  643,  642,  686,  252,  790,
      688,  366,  370,  377,  384,  407,  411,  360,  790,  256,
      416,  790,  425,  378,    0,  433,  670,  183,  643,    0,
      434,  232,    0,  450,  622,  607,  606,  600,    0,  591,
        0,  575,  577,    0,    0,  564,  566,  559,  542,  554,
      522,    0,  502,  503,    0,  509,  516,  508,  503,  495,
      504,  490,  498,  497,  483,  490,    0,  476,  475,    0,
        0,  468,  480,  476,  457,  462,  473,  487,  424,  503,
      455,  790,  475,  474,  471,  453,  468,    0,    0,    0,

      455,  455,  447,    0,  444,  434,  441,  427,  405,  403,
      416,  411,  400,  408,    0,  405,  362,    0,  363,  358,
      364,  358,    0,    0,  420,  510,  363,    0,  346,    0,
      335,  318,  332,  327,    0,  328,  311,  320,  301,    0,
        0,    0,    0,  312,  286,    0,  294,  287,  515,  790,
      524,  277,    0,    0,    0,  281,  278,  271,    0,    0,
      275,  254,  255,  253,  256,    0,  242,  245,  252,  247,
        0,  235,  222,    0,  213,  212,  202,    0,  176,    0,
        0,    0,  790,  165,  164,    0,  790,  565,  576,  587,
      598,  605,  616,  627,  638,  649,  660,  665,  667,  190,

      669,  176,  674,  678,  682
    } ;

static const flex_int16_t yy_def[406] =
    {   0,
      387,    1,  388,  388,  389,  389,  390,  390,  387,  387,
      387,  387,  387,  387,  391,  392,  387,  387,  393,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  387,  387,  387,  387,  394,
      387,  395,  396,  387,  387,  397,  387,  387,  387,  387,
      391,  387,  392,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  398,
      387,  399,   29,  387,  387,  387,  387,  387,  387,  387,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  387,
      394,  395,  395,  387,  396,  397,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,   84,  387,  387,
      387,  387,  387,  387,  400,  401,  402,  403,   93,  387,
       93,  387,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  404,  400,  401,  387,  236,  405,  402,
      403,  241,  171,  387,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  387,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  387,  387,  387,  387,  404,  387,
      404,  387,  405,  405,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  387,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  387,  387,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  387,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  387,  387,
      387,  392,  392,  392,  392,  392,  392,  387,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  387,  392,
      392,  392,  392,  392,  392,  392,  387,  392,  392,  392,
      392,  392,  387,  392,  392,  392,    0,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387
    } ;

static const flex_int16_t yy_nxt[860] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       29,   29,   30,   31,   32,   33,   34,   35,   36,   16,
       16,   16,   16,   16,   16,   16,   37,   10,   38,   39,
       16,   40,   41,   42,   43,   44,   45,   16,   16,   46,
       16,   47,   16,   48,   16,   49,   50,   51,   52,   16,
       53,   54,   16,   55,   16,   56,   57,   58,   59,   61,
       61,   64,   65,   64,   65,   67,   67,   75,   77,   62,
       62,   78,   79,   81,   80,   80,   80,   80,   82,  101,
       74,   74,   96,   97,   74,  106,   74,   99,  100,   74,

      204,  103,  107,  104,  102,  108,  125,   68,   68,   83,
      105,   84,   84,   84,   85,  205,  110,  126,  111,  136,
      127,  113,  134,   86,   87,   88,   89,  112,   90,  114,
      135,  115,  137,   91,  116,   86,  117,   87,   88,   87,
      140,  143,  118,  119,   89,  198,  144,  162,  162,  121,
      199,  129,  387,  122,  130,   92,   83,  387,   93,   93,
       93,   93,  123,  208,  131,  132,  214,  124,  215,  133,
      209,   87,   88,   89,  152,  152,  152,  152,   74,  172,
       94,  190,  191,  239,   87,   88,   87,  153,  154,  228,
      228,   89,  156,  156,  156,  156,  155,  234,  143,  387,

      153,  154,  153,  144,  229,   87,  157,  163,  386,  163,
      385,  230,  164,  164,  164,  164,  387,  210,   87,  157,
       87,   83,  229,  158,  158,  158,   85,  219,  220,  221,
       84,   84,   84,   85,  387,  211,   87,   88,  159,  212,
      384,  169,  169,  169,  169,  160,  383,  235,  387,   87,
       88,   87,   91,  219,  220,  221,  159,   83,  382,   85,
       85,   85,   85,  170,  237,  387,  171,  171,  171,  171,
      381,  238,   87,   88,  228,  228,  152,  152,  152,  152,
      380,  161,  237,  387,  379,   87,   88,   87,   94,  153,
      154,  378,  152,  152,  152,  152,  230,  377,  155,  376,

      375,  374,  153,  154,  153,  222,  373,  222,  372,  371,
      223,  223,  223,  223,  155,  224,  224,  224,  224,  226,
      370,  226,  369,  368,  227,  227,  227,  227,   87,  157,
      158,  158,  158,   85,  367,  366,  240,  225,  365,  364,
      363,   87,  157,   87,   85,   85,   85,   85,  164,  164,
      164,  164,  160,  237,  231,  231,  231,  231,  362,  361,
      242,  169,  169,  169,  169,  360,  161,  232,  359,  358,
      357,  237,  243,  243,  243,  243,  233,  356,  228,  228,
      232,  355,  232,  170,  223,  223,  223,  223,  285,  285,
      285,  285,  354,  229,  244,  224,  224,  224,  224,  353,

      230,  153,  224,  224,  224,  224,  352,  348,   87,  157,
      286,  229,  290,  347,  153,  346,  153,  225,  291,  345,
      344,   87,  157,   87,  225,  227,  227,  227,  227,  287,
      287,  287,  287,  290,  231,  231,  231,  231,  326,  326,
      326,  326,   87,  231,  231,  231,  231,  232,  343,  235,
      240,  288,  342,  341,  340,   87,  233,   87,  290,  339,
      232,  338,  232,  337,  291,  233,  237,  237,  243,  243,
      243,  243,  336,  238,  242,  285,  285,  285,  285,  290,
      285,  285,  285,  285,  237,  237,  335,  334,  153,  387,
      244,  287,  287,  287,  287,  291,  333,  286,  332,  331,

      330,  153,  286,  153,   87,  287,  287,  287,  287,  329,
      387,  328,  327,  288,  294,  294,  325,   87,  325,   87,
      324,  326,  326,  326,  326,  323,  322,  288,  349,  349,
      349,  349,  321,  349,  349,  349,  349,  320,  319,  318,
      317,  350,  349,  349,  349,  349,  350,  316,  315,  314,
      351,  313,  312,  311,  350,  351,  350,  310,  309,  350,
      308,  350,  307,  306,  351,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   71,  305,

      304,   71,   71,   71,   71,   71,   71,   71,   71,   73,
      303,  280,   73,   73,   73,   73,   76,  302,   76,   76,
       76,   76,   76,   76,   76,   76,   76,  141,  301,  141,
      141,  141,  300,  141,  141,  141,  141,  141,  142,  299,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  145,
      298,  297,  145,  145,  145,  145,  145,  145,  145,  145,
      146,  146,  146,  296,  146,  146,  146,  146,  146,  146,
      146,  166,  166,  168,  168,  236,  236,  236,  295,  236,
      241,  241,  241,  294,  241,  289,  292,  289,  289,  293,
      220,  218,  293,  284,  283,  282,  281,  280,  279,  278,

      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,   74,  218,  217,  216,  213,  207,  206,
      203,  202,  201,  200,  197,  196,  195,  194,  193,  192,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,   74,  167,  165,
      151,  150,  149,  148,  147,  139,  138,  128,  120,  109,
       74,   98,   95,   74,   74,   72,   70,   69,  387,    9,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387
    } ;

static const flex_int16_t yy_chk[860] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    5,    5,    6,    6,    7,    8,   18,   23,    3,
        4,   25,   26,   27,   26,   26,   26,   26,   27,   40,
       23,   25,   32,   32,   18,   42,   27,   34,   34,   57,

      131,   41,   42,   41,   40,   42,   49,    7,    8,   28,
       41,   28,   28,   28,   28,  131,   44,   49,   44,   53,
       49,   45,   52,   28,   28,   28,   28,   44,   28,   45,
       52,   45,   53,   28,   45,   28,   46,   28,   28,   28,
       57,   62,   46,   46,   28,  126,   62,   86,   86,   48,
      126,   51,  142,   48,   51,   28,   29,  142,   29,   29,
       29,   29,   48,  134,   51,   51,  137,   48,  137,   51,
      134,   29,   29,   29,   80,   80,   80,   80,  100,  100,
       29,  119,  119,  402,   29,   29,   29,   80,   80,  162,
      162,   29,   83,   83,   83,   83,   80,  400,  143,  238,

       80,   80,   80,  143,  162,   83,   83,   88,  385,   88,
      384,  162,   88,   88,   88,   88,  238,  135,   83,   83,
       83,   84,  162,   84,   84,   84,   84,  149,  149,  149,
       91,   91,   91,   91,  238,  135,   84,   84,   84,  135,
      379,   93,   93,   93,   93,   84,  377,  166,  242,   84,
       84,   84,   91,  219,  219,  219,   84,   85,  376,   85,
       85,   85,   85,   93,  166,  242,   94,   94,   94,   94,
      375,  166,   85,   85,  230,  230,  152,  152,  152,  152,
      373,   85,  166,  242,  372,   85,   85,   85,   94,  152,
      152,  370,  155,  155,  155,  155,  230,  369,  152,  368,

      367,  365,  152,  152,  152,  154,  364,  154,  363,  362,
      154,  154,  154,  154,  155,  156,  156,  156,  156,  157,
      361,  157,  358,  357,  157,  157,  157,  157,  156,  156,
      160,  160,  160,  160,  356,  352,  168,  156,  348,  347,
      345,  156,  156,  156,  161,  161,  161,  161,  163,  163,
      163,  163,  160,  168,  164,  164,  164,  164,  344,  339,
      168,  170,  170,  170,  170,  338,  161,  164,  337,  336,
      334,  168,  171,  171,  171,  171,  164,  333,  228,  228,
      164,  332,  164,  170,  222,  222,  222,  222,  223,  223,
      223,  223,  331,  228,  171,  224,  224,  224,  224,  329,

      228,  223,  225,  225,  225,  225,  327,  322,  224,  224,
      223,  228,  234,  321,  223,  320,  223,  224,  234,  319,
      317,  224,  224,  224,  225,  226,  226,  226,  226,  227,
      227,  227,  227,  234,  231,  231,  231,  231,  325,  325,
      325,  325,  227,  233,  233,  233,  233,  231,  316,  236,
      241,  227,  314,  313,  312,  227,  231,  227,  289,  311,
      231,  310,  231,  309,  289,  233,  236,  241,  244,  244,
      244,  244,  308,  236,  241,  285,  285,  285,  285,  289,
      286,  286,  286,  286,  236,  241,  307,  306,  285,  291,
      244,  287,  287,  287,  287,  291,  305,  285,  303,  302,

      301,  285,  286,  285,  287,  288,  288,  288,  288,  297,
      291,  296,  295,  287,  294,  293,  290,  287,  290,  287,
      284,  290,  290,  290,  290,  283,  282,  288,  326,  326,
      326,  326,  279,  349,  349,  349,  349,  278,  276,  275,
      274,  326,  351,  351,  351,  351,  349,  273,  272,  271,
      326,  270,  269,  268,  326,  349,  326,  267,  266,  349,
      264,  349,  263,  261,  351,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  391,  260,

      259,  391,  391,  391,  391,  391,  391,  391,  391,  392,
      258,  257,  392,  392,  392,  392,  393,  256,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  394,  253,  394,
      394,  394,  252,  394,  394,  394,  394,  394,  395,  250,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  396,
      248,  247,  396,  396,  396,  396,  396,  396,  396,  396,
      397,  397,  397,  246,  397,  397,  397,  397,  397,  397,
      397,  398,  398,  399,  399,  401,  401,  401,  245,  401,
      403,  403,  403,  239,  403,  404,  237,  404,  404,  405,
      221,  218,  405,  217,  216,  215,  214,  211,  210,  209,

      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  193,  192,  190,  189,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  147,  139,  138,  136,  133,  132,
      130,  129,  128,  127,  125,  124,  123,  122,  121,  120,
      118,  116,  115,  114,  113,  112,  111,  110,  109,  108,
      107,  106,  105,  104,  103,  102,  101,   96,   92,   90,
       79,   76,   72,   71,   67,   55,   54,   50,   47,   43,
       39,   33,   30,   22,   17,   15,   14,   13,    9,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[112] =
    {   0,
1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
    #include <iostream>
    #include <stdio.h>
    #include "parser.tab.h"
    using namespace std;

    #define YY_DECL extern "C" int yylex()
    void err (const char* s)
    {
        if(s == NULL) {
            printf("Error in memory allocation");
            exit(0);
        }
    }

    string tb;

    // case, const, default, do, goto, import, interface, package, switch, underscore, exports, module, open, opens, provides, record, requires, to, transitive, uses, with
#line 812 "lex.yy.c"

#line 814 "lex.yy.c"

#define INITIAL 0
#define comment1 1
#define comment2 2
#define textblock 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 55 "lexer.l"

#line 1036 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 388 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 790 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 56 "lexer.l"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "lexer.l"

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "lexer.l"
{ BEGIN comment1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "lexer.l"

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "lexer.l"

	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 62 "lexer.l"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "lexer.l"
{ BEGIN 0; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "lexer.l"
{ BEGIN comment2; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 "lexer.l"

	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 67 "lexer.l"
{ BEGIN 0; }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 69 "lexer.l"
{ 
    BEGIN textblock; 
    tb = yytext;
}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 73 "lexer.l"
{ tb += yytext; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 74 "lexer.l"
{ 
    cerr << "Illegal \\ inside text block found at line: " << yylineno << '\n';
    BEGIN 0;
    return 0;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 79 "lexer.l"
{ tb += yytext; }
	YY_BREAK
case YY_STATE_EOF(textblock):
#line 80 "lexer.l"
{ 
    cerr << "Unfinished textblock. Aborting!" << '\n';
    BEGIN 0;
    return 0; 
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "lexer.l"
{ 
    tb += yytext; 
    tb = "";

    return (LITERAL_textblock);
    BEGIN 0; 
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return (DELIM_semicolon); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 94 "lexer.l"
{ return (DELIM_period); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return (DELIM_lpar); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return (DELIM_rpar); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return (DELIM_lsq); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return (DELIM_rsq); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return (DELIM_lcurl); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return (DELIM_rcurl); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 101 "lexer.l"
{ return (DELIM_comma); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 102 "lexer.l"
{ return (DELIM_ellipsis); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return (DELIM_proportion); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return (DELIM_attherate); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return (KEYWORD_abstract); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return (KEYWORD_assert); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return (KEYWORD_boolean); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return (KEYWORD_break); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return (KEYWORD_byte); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return (KEYWORD_catch); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return (KEYWORD_char); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return (KEYWORD_class); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return (KEYWORD_double); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return (KEYWORD_else); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return (KEYWORD_enum); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return (KEYWORD_extends); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return (KEYWORD_final); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return (KEYWORD_finally); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return (KEYWORD_float); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return (KEYWORD_for); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return (KEYWORD_if); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return (KEYWORD_implements); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 124 "lexer.l"
{ return (KEYWORD_instanceof); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return (KEYWORD_int); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return (KEYWORD_long); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 127 "lexer.l"
{ return (KEYWORD_native); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return (KEYWORD_new); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return (KEYWORD_private); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return (KEYWORD_protected); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 131 "lexer.l"
{ return (KEYWORD_public); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return (KEYWORD_return); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return (KEYWORD_short); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return (KEYWORD_static); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return (KEYWORD_strictfp); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return (KEYWORD_super); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 137 "lexer.l"
{ return (KEYWORD_synchronized); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 138 "lexer.l"
{ return (KEYWORD_this); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 139 "lexer.l"
{ return (KEYWORD_throw); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 140 "lexer.l"
{ return (KEYWORD_throws); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 141 "lexer.l"
{ return (KEYWORD_transient); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return (KEYWORD_try); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return (KEYWORD_void); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return (KEYWORD_volatile); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return (KEYWORD_while); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return (KEYWORD_nonsealed); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 149 "lexer.l"
{ return (KEYWORD_permits); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 150 "lexer.l"
{ return (KEYWORD_sealed); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return (KEYWORD_var); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 152 "lexer.l"
{ return (KEYWORD_yield); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 154 "lexer.l"
{ return (OPERATOR_equal); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 155 "lexer.l"
{ return (OPERATOR_bitwiseand); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 156 "lexer.l"
{ return (OPERATOR_ternaryquestion); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 157 "lexer.l"
{ return (OPERATOR_ternarycolon); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 158 "lexer.l"
{ return (OPERATOR_logicalor); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 159 "lexer.l"
{ return (OPERATOR_logicaland); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 160 "lexer.l"
{ return (OPERATOR_bitwiseor); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 161 "lexer.l"
{ return (OPERATOR_xor); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 162 "lexer.l"
{ return (OPERATOR_logicalequal); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 163 "lexer.l"
{ return (OPERATOR_neq); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 164 "lexer.l"
{ return (OPERATOR_lt); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 165 "lexer.l"
{ return (OPERATOR_gt); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 166 "lexer.l"
{ return (OPERATOR_leq); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 167 "lexer.l"
{ return (OPERATOR_geq); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 168 "lexer.l"
{ return (OPERATOR_leftshift); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 169 "lexer.l"
{ return (OPERATOR_rightshift); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 170 "lexer.l"
{ return (OPERATOR_unsignedrightshift); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 171 "lexer.l"
{ return (OPERATOR_plus); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 172 "lexer.l"
{ return (OPERATOR_minus); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 173 "lexer.l"
{ return (OPERATOR_multiply); } 
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 174 "lexer.l"
{ return (OPERATOR_divide); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 175 "lexer.l"
{ return (OPERATOR_mod); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 176 "lexer.l"
{ return (OPERATOR_increment); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 177 "lexer.l"
{ return (OPERATOR_decrement); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 178 "lexer.l"
{ return (OPERATOR_bitwisecomp); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 179 "lexer.l"
{ return (OPERATOR_not); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 180 "lexer.l"
{ return (OPERATOR_assignment); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 182 "lexer.l"
{ yylval.numval = stol(yytext); return (LITERAL_integer); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 183 "lexer.l"
{ yylval.numval = stol(((string) yytext).substr(2, ((string) yytext).length()-2), 0, 16); return (LITERAL_integer); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 184 "lexer.l"
{ yylval.numval = stol(yytext, 0, 8); return (LITERAL_integer); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 185 "lexer.l"
{ yylval.numval = stol(((string) yytext).substr(2, ((string) yytext).length()-2), 0, 2) ; return (LITERAL_integer); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 186 "lexer.l"
{ yylval.realval = stold(yytext); return (LITERAL_floatingpoint); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 187 "lexer.l"
{ return (LITERAL_boolean); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 188 "lexer.l"
{ yylval.charval = yytext[0]; return (LITERAL_char); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 189 "lexer.l"
{ strcpy(yylval.strval, yytext); return (LITERAL_string); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 190 "lexer.l"
{ return (LITERAL_null); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 192 "lexer.l"
{ return (Identifier); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 194 "lexer.l"
{
    cerr << "Unknown character " << yytext << " found at line: " << yylineno << "\n";
    return 0;
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 198 "lexer.l"
ECHO;
	YY_BREAK
#line 1687 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment1):
case YY_STATE_EOF(comment2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 388 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 388 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 387);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 198 "lexer.l"

